### ISSUE TITLE
Latex graph 

### ISSUE THREAD

**Issue by joshuapeters0210** [causalincentives/cid-latex#1]
Hey, i've been using this code. When creating graphs with three players the utility node becomes yellow, while the decision node becomes purple. Is there a way to add a third player? all the best.

**Comment by tom4everitt** [comment]
My guess is that you do something like

```\node [player3, utility] {$U_3$}```

instead of 

```\node [utility, player3] {$U_3$}```

which means that the default utility color overrides the color specified by player3.

(I wish there was an easy way to avoid this, so that utility doesn't override, but I haven't found one.)

**Comment by joshuapeters0210** [comment]
![image](https://user-images.githubusercontent.com/76959715/112509577-8583ad00-8d88-11eb-9ba6-6b9d5c36b5a0.png)

I've quickly tested this but it still does decision and utility nodes as different colours. I've attached a quick screenshot. Thanks!

**Comment by tom4everitt** [comment]
Interesting, that odd. Can you actually copy-paste the code, rather than just screenshot it? Ideally along with just the part of your preamble that's needed to reproduce. That would make it so much easier for me to debug this! :) 

Thanks for raising this!

**Comment by tom4everitt** [comment]
In particular,

```latex
\documentclass{article}
\usepackage[decisionutilitycolor]{influence-diagrams}

\begin{document}

\begin{influence-diagram}
  \node (D3) [decision, player3] {$D_3$};
  \node (U3) [below=of D3, utility, player3] {$U_3$};
\end{influence-diagram}

\end{document}
```

works fine for me, producing:

![image](https://user-images.githubusercontent.com/8945670/112523262-7c99d800-8d96-11eb-8e4b-1add78da4e39.png)

(note that the color for player3 is actually yellow; up to player6 is supported by the package)

**Comment by joshuapeters0210** [comment]
I fixed the issue, thanks! After using your code and still getting the same issue I checked my influence-diagram.sty which has the date from 2020-09-06. 

When clicking on the casual influence diagram tutorial and following the page down to setup. The link for the influence-diagram .sty there is from 2020-09-06 which has the code 

\RequirePackage{xcolor}
\colorlet{good-color}{green}
\colorlet{bad-color}{red}
\colorlet{player1-color}{orange!30}
\colorlet{player2-color}{green!30}
\colorlet{common-color}{brown!20}

rather than the newer code 

% Primary colours
\colorlet{player1-color}{red!30}
\colorlet{player2-color}{blue!30}
\colorlet{player3-color}{yellow!30}
% Secondary colours
\colorlet{player4-color}{green!30}
\colorlet{player5-color}{purple!30}
\colorlet{player6-color}{orange!30}
% Mixed colour
\colorlet{common-color}{brown!20}

Thanks for the help getting this sorted so quick!

**Comment by tom4everitt** [comment]
Ah, that explains it! Glad to hear it's working again. Don't hesitate to bring up other issues you might find.
